### ISSUE TITLE
Screen power supply emitting noise

### ISSUE THREAD

**Issue by max-circlefade** [linusg/rpi-backlight#11]
Hey everyone, 

I managed to run the code to change screen brightness and every thing works fine.

However for low brightness values (<100) the screen power supply starts emitting some noise.
Any one knows why ? 
Could it be related to brightness being the screen turning on et off quickly so the power supply becomes some kind of square signal ?

**Comment by WestleyK** [comment]
That’s very weird, are you using the official 7 inch Raspberry Pi touch
screen?
The PWM(pulse width modulation) frequency should be > 20khz, maybe there’s
a faulty capacitor on your board, or something else that’s causing that
noise ;)

BTW, PWM is that square wave thingy you were talking about.

**Comment by max-circlefade** [comment]
Hey, 
Thanks for the quick answer. Yes I'm using the official touchscreen, with its dedicated power supply. Actually it is a cheap phone one so issue might be linked to that as well.

The fact it is in deed a PWM on off method explains half of the problem.

Is there a way to know the commutation frequency somewhere in the code ? If so I will run some calculations to see if freq could be less than 20kHZ for low brightness values.

**Comment by max-circlefade** [comment]
Hey
Thanks that would be great :)
Now that I think about it the answer regarding the PWM freq should be defined in the touch screen firmware.. but it doesn't seem to be open source. Will also continue investigating on my side!

**Comment by WestleyK** [comment]
Try using a bigger power supply, one with more output current, like 2.5A at
least. That display uses a lot of power.

**Comment by WestleyK** [comment]
You can also try to turn off the backlight:
```
$ sudo bash -c "echo 1 > /sys/class/backlight/rpi_backlight/bl_power"
```
Then see if its still emitting that noise.

*Make sure you are `ssh` into the pi, otherwise it will be hard to turn it back on ;)*
*`echo 0` to turn it back on.*

**Comment by linusg** [comment]
Well, since this is the rpi-backlight repository you might as well use the Python API for turning the backlight off (which, frankly, uses the same command under the hood) 😂

Response from the forum so far: does it hapenn with another psu as well? Those from phones are made for charging and not stable voltage and usually not recommended.
