### ISSUE TITLE
Raspbian Buster Lite

### ISSUE THREAD

**Issue by MrMoins** [linusg/rpi-backlight#15]
Hi.
I'm trying to use rpi-backlight on a raspberry-pi using Raspbian Buster Lite and the official 7" touchscreen.

I got the error `/sys/class/backlight/rpi_backlight/bl_power: No such file or directory` when I try to power off with `rpi-backlight --p off`

Directory `/sys/class/backlight` is empty.

Do I need to install some dependencies?

**Comment by linusg** [comment]
> Do I need to install some dependencies?

Not that I'm aware of. Please make sure the display ist connected properly and get in touch with the raspberry pi kernel developers - I'm unable to troubleshoot issues not directly related to this project.
