### ISSUE TITLE
possibility to set time in seconds, after which the screen will turn off automatically and wakes up on touch again

### ISSUE THREAD

**Issue by Qlink84** [linusg/rpi-backlight#22]
i would love the feature to set a time in seconds after which the screen will turn off/fade automatically and if a touch on the screen happens it wakes up again to full or defined brightness... like it happens on every smartphone...

the tool backlight_dimmer (https://github.com/DougieLawson/backlight_dimmer) does something similar but has some bugs ... it just recognizes input from keyboard after some time and not from touchscreen and or mouse ... and it seems like the dev is gone also so no bug fixes :(

**Comment by linusg** [comment]
That's definitely out of scope for this project, but you can easily write a script specific to your environment to do so.

> and it seems like the dev is gone

That's not true, their last activity here on GitHub was 10 days ago. File an issue in the backlight_dimmer repository.

**Comment by nathanRamaNoodles** [comment]
Does this fork work for you: https://github.com/nathanRamaNoodles/backlight_dimmer
