### ISSUE TITLE
GUI Permissions

### ISSUE THREAD

**Issue by p1r473** [linusg/rpi-backlight#23]
Hi Linus!
I have ran the following command:
```
echo 'SUBSYSTEM=="backlight",RUN+="/bin/chmod 666 /sys/class/backlight/%k/brightness /sys/class/backlight/%k/bl_power /sys/devices/platform/ff150000.i2c/i2c-3/3-0045/tinker_mcu_bl
"' | sudo tee -a /etc/udev/rules.d/backlight-permissions.rules
```
Note, I ran for both the TinkerBoard and the Pi files, as all files exist on my OS.
This does not fix the permissions for me.

Sidenote, I actually had to replace the %k with rpi_backlight:

```
echo 'SUBSYSTEM=="backlight",RUN+="/bin/chmod 666 /sys/class/backlight/rpi_backlight/brightness /sys/class/backlight/rpi_backlight/bl_power /sys/devices/platform/ff150000.i2c/i2c-3/3-0045/tinker_mcu_bl
> "' | sudo tee -a /etc/udev/rules.d/backlight-permissions.rules
```

 as I got:
```
chmod: cannot access '/sys/class/backlight/%k/brightness': No such file or directory
chmod: cannot access '/sys/class/backlight/%k/bl_power': No such file or directory
```

Just wondering if you have any idea why both the udev rule wouldn't work, nor the %k in that rule?

**Comment by p1r473** [comment]
I've created a workaround:

```cat /etc/systemd/system/setbacklightpermissions.service```
[Unit]
Description=Set backlight writable by everybody

[Service]
Type=simple
User=root
ExecStart=/bin/chmod 666 /sys/class/backlight/rpi_backlight/brightness /sys/class/backlight/rpi_backlight/bl_power /sys/devices/platform/ff150000.i2c/i2c-3/3-0045/tinker_mcu_bl

[Install]
WantedBy=multi-user.target
```

then ran:
```
sudo systemctl enable setbacklightpermissions.service
sudo systemctl start setbacklightpermissions.service
```

**Comment by linusg** [comment]
Hi @p1r473,

I'm afraid I have no idea what's going on there. `%k` should work as described in the `udev` manpage:

> https://linux.die.net/man/8/udev
> ...
> %k - The "kernel name" for the device.

Might be something specific to the Tinker Board OS? Never used it, can't investigate.

Using Systemd for this is a bad workaround IMO :smile:
See if there are other rules on your system which do similar stuff, maybe you can spot differences.

>  This does not fix the permissions for me.

Did you try, without having the Systemd unit enabled, what happens after a reboot? Or `sudo udevadm trigger`?

**Comment by p1r473** [comment]
Not sure why the %k's weren't working, but seem to be working now.
So after running
```
 systemctl disable setbacklightpermissions

echo 'SUBSYSTEM=="backlight",RUN+="/bin/chmod 666 /sys/class/backlight/%k/brightness /sys/class/backlight/%k/bl_power /sys/devices/platform/ff150000.i2c/i2c-3/3-0045/tinker_mcu_bl
"' | sudo tee -a /etc/udev/rules.d/backlight-permissions.rules
reboot
```
No luck with GUI permissions
then:
```
sudo udevadm trigger
```

Still no luck. Is it possible that my subsystem is not called backlight, so this does not ever run? How can I find my subsystem name?

**Comment by p1r473** [comment]
Okay, still tweaking, but I got it to the point where 
```sudo udevadm trigger``` works:

SUBSYSTEM=="spidev", ACTION=="change", RUN+="/bin/chmod 666 /sys/class/backlight/rpi_backlight/brightness /sys/class/backlight/rpi_backlight/bl_power /sys/devices/platform/ff150000.i2c/i2c-3/3-0045/tinker_mcu_bl"


Any idea why it wouldn't trigger, or whats the best subsystem to use?

**Comment by p1r473** [comment]
Not sure if it was a problem with the echo or the tee, but just manually creating the file seems to work:
/etc/udev/rules.d/backlight-permissions.rules:
```
SUBSYSTEM=="backlight",RUN+="/bin/chmod 666 /sys/class/backlight/%k/brightness /sys/class/backlight/%k/bl_power /sys/devices/platform/ff150000.i2c/i2c-3/3-0045/tinker_mcu_bl"
```

Thanks!

**Comment by linusg** [comment]
Weird! Glad you got it working though, thanks for reporting back!
