### ISSUE TITLE
How to update existing installation

### ISSUE THREAD

**Issue by Rebel154** [linusg/rpi-backlight#24]
I currently have V2.0.0 installed on 2 Raspberry Pi's. Could you explain how to update these installations to the current release version please.

I've tried the following command:

`pip3 install rpi-backlight`

but it just returns 
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: rpi-backlight in ./.local/lib/python3.7/site-packages (2.0.0)
```
Thank you.

**Comment by linusg** [comment]
```
pip3 install --upgrade rpi-backlight
```

https://pip.pypa.io/en/stable/quickstart/#quickstart
