### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by aareben** [linusg/rpi-backlight#25]
Whenever I try to use rpi-backlight, i get command not found. I'm not too good at linux so I probably skipped a step or did something wrong. Any help would be great.

**Comment by linusg** [comment]
If you used pip to install it will likely have ended up in `/home/user/pi/.local/bin`. Try if this works:

```
$ /home/user/pi/.local/bin/rpi-backlight --version
```

if so, you'll simply have to add that directory to your `PATH` - edit `~/.bashrc` (assuming you're using the bash) and add this line:

```
export PATH="$HOME/.local/bin:$PATH"
```
