### ISSUE TITLE
 Problem with installing rpi backlight on Volumio.org

### ISSUE THREAD

**Issue by tomikwr** [linusg/rpi-backlight#26]
Hello

I have installed the latest Volumio and am having trouble installing a button script that can control the official display backlight for Raspberry Pi.

The full tutorial I use is on this forum:
https://community.volumio.org/t/guide-for-setting-up-touchscreen-backlight-control/9666

First I install "Python GPIO", then "Python backlight library" and when installing "sudo pip install rpi_backlight" it encounters an error that I cannot solve. I would like to add that the old version of Volumio from 2 years ago installed without any problems and everything worked as it should.

Sorry for my english but this is google translation.

Below is a photo with this error.
![blad](https://user-images.githubusercontent.com/73463648/97147513-ecfde800-1769-11eb-9f9c-857b12393409.jpg)

I would like to ask for your help because I care about this function. Thank you. Thomas :)

**Comment by linusg** [comment]
This happens when you use a version of Python < 3.5, which is not supported by this project (even 3.5 itself has reached end of life).

The tutorial seems to use Python 2, just use 3. :)

**Comment by tomikwr** [comment]
Thank you for your response. Unfortunately, I still have a problem with that. I install as below but there are still bugs. Unless I saw it wrong?

Python GPIO:
wget https://sourceforge.net/projects/raspberry-gpio-python/files/raspbian-wheezy/python3-rpi.gpio_0.6.2~wheezy-1_armhf.deb

Install:
sudo dpkg -i python3-rpi.gpio_0.6.2~wheezy-1_armhf.deb

Please help. Thank you.

**Comment by linusg** [comment]
rpi-backlight has no 3rd-party dependencies, therefore this is completely unrelated. If it's from that tutorial you mentioned, please ask its author instead. Generally speaking though, no one will be able to help you if you're not giving them more detailed descriptions - you mention problems/"bugs" but don't specify what happens.

**Comment by tomikwr** [comment]
Sorry for the lack of specificity. After entering the above command, the error like below pops up.

![blad2](https://user-images.githubusercontent.com/73463648/97160458-af568a80-177c-11eb-82af-0cbb21bd2b7f.jpg)
