### ISSUE TITLE
Improvement to gui

### ISSUE THREAD

**Issue by CerberusStyle** [linusg/rpi-backlight#27]
If the gui had on and off buttons for the display it would then be perfect.

**Comment by linusg** [comment]
PRs welcome, though I don't think that's super useful as turning a display that's been turned off back on could be quite difficult unless you can remember the button's position precisely.

**Comment by CerberusStyle** [comment]
should not be that hard at all here is how its done in BASH so you should be able to do it in python i would do it myself but im not great at python.
`#!/bin/bash

if [ $# -eq 0 ] || [[ $1 != "on"  &&  $1 != "off" ]]; then
  echo "Usage: rpi-backlight [on/off]"
  exit 1
fi

output=$(tvservice -s)

if [[ $output =~ "0x400000 [LCD]" ]]; then

  # Official 7" display
  if [ $1 = "on" ]; then
    echo 0 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
  elif [ $1 = "off" ]; then
    echo 1 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
  fi

fi`
