### ISSUE TITLE
changing brightness makes rpi crash after a while.

### ISSUE THREAD

**Issue by pjmpessers** [linusg/rpi-backlight#28]
I recently installed rpi-backlight v2.2.0 and i can change the brightness of the original 7" touch screen version v1.1 with a Raspberry pi model 4B + 4 gb. So i'm happy about that. But i noticed when i use rpi-backlight and it's not set to 100% it just crashes after a while. Doesn't matter if it's set at 50, 8, 5, etc %. It can take a few minutes or hour, but it will crash.
Also removing a USB-stick or USB-keyboard results could result in a crash, so the screen or raspberry pi are very unstable. Not when it's set at 100%. I use a 5V/3A power brick, so there would be enough current.

Could you help me?

Thanks

**Comment by linusg** [comment]
This tool merely communicates with the driver built into the kernel via sysfs, so no, I can't fix this issue. File an issue on the Raspberry Pi kernel repository instead.
Do note though that 5V may not be sufficient, for RPi's >= 3 it's usually recommended to use 5.1V to account for a small voltage drop (the offical PSU has this voltage as well).

**Comment by pjmpessers** [comment]
Thank you. I will ask them if they have a solution for it.

**Comment by pjmpessers** [comment]
You where right. The problem was the power brick. I have 2 raspberry pi model 4b and 2 5.2V/5A powerbricks that are exactly the same. One raspi is connected with a HDMI monitor so not using the rpi-backlight and the other one has the original touchpi screen. I switched the powerbricks to find out if it helps. And it did. So even when they looks the identical they act different. Now i can use rpi-backlight without it crashing and the second raspi is stable without a touchpi screen attached.
