### ISSUE TITLE
-bash: rpi-backlight: command not found

### ISSUE THREAD

**Issue by Marco-exports** [linusg/rpi-backlight#37]
When typing this:

**pi@DALI:~ $ rpi-backlight --get-power**

I get this error:

**-bash: rpi-backlight: command not found**

How can I run this from any directory ?

**Comment by linusg** [comment]
Add the install directory, presumably `~/.local/bin`, to the shell's `$PATH`.

**Comment by Marco-exports** [comment]
Your short answers leave me completely confused !!!

I followed your instruction manuals, but have no idea where these errors are coming from.  I wish you would do a better set of instructions, as I cannot figure out anything you are saying now.
