### ISSUE TITLE
rpi-backligth --power is always false

### ISSUE THREAD

**Issue by Jannis1337** [linusg/rpi-backlight#4]
Hi,
when I run "rpi-backligth --power" as a command it always return FASLE

```
pi@raspberrypi:~ $ rpi-backlight --actual-brightness
255
pi@raspberrypi:~ $ rpi-backlight --off
pi@raspberrypi:~ $ rpi-backlight --power
False
pi@raspberrypi:~ $ rpi-backlight --on
pi@raspberrypi:~ $ rpi-backlight --power
False
pi@raspberrypi:~ $
```

**Comment by linusg** [comment]
Hi,
thanks for the report! I'm actually REALLY happy that someone uses this code. Will look into it, wait a minute or two...

:grinning:

**Comment by linusg** [comment]
OK. That's a stupid one, sorry for that. Would you mind pulling the latest changes and testing it again? I have no Pi running for now, that would be great help :wink:

```
cd ~
git clone https://github.com/linusg/rpi-backlight.git
cd rpi-backlight
python3 rpi_backlight.py --off
python3 rpi_backlight.py --power
python3 rpi_backlight.py --on
python3 rpi_backlight.py --power
```

Otherwise you will have to wait until it's on PyPI so you can update then.

Again, thanks for reporting!

**Comment by linusg** [comment]
Should be fixed with https://github.com/linusg/rpi-backlight/commit/225a68c777c7a6e71e87b1f73a77259c3a01400f, in release 1.7.0 (already on PyPI). Not tested but damn this should work now.

**Comment by Jannis1337** [comment]
Yes now it works! Thank you for really quick fixing
