### ISSUE TITLE
Suggested UDEV rule not triggering?

### ISSUE THREAD

**Issue by LarryGFlorence** [linusg/rpi-backlight#46]
Running: Raspberry Pi 4 Model B Rev 1.4, Debian GNU/Linus 11 (bullseye), aarch64.
Attached: Raspberry Pi 7" Touchscreen Display

Problem: cmdline rpi-backlight -b 50 returns "Permission Error". 
Reason: /sys/class/backlight/10-0045/brightness is owned by root, permissions=644.
Cause: Suggested UDEV rule (SUBSYSTEM=="backlight") is not being triggered. Permissions are not modified upon startup.

How to debug? How to fix?

**Comment by linusg** [comment]
> How to debug? How to fix?

I don't know. Unfortunately, I don't have a working display right now. I'm sure you can find information on debugging udev online though, good luck!

**Comment by LarryGFlorence** [comment]
I added this line to the end of my ~/.bashrc script. It solves the problem until the UDEV triggering issue can be figured out:

sudo /bin/chmod 666 /sys/class/backlight/10-0045/brightness /sys/class/backlight/10-0045/bl_power

I derived the "kernel" number by following the /sys/class/backlight path.
