### ISSUE TITLE
Bullseye Issue

### ISSUE THREAD

**Issue by matmal** [linusg/rpi-backlight#49]
Hi,
Running in the CLI rpi-backlight produces strange errors. I do not know if due to the fact that Bullseye brings changes internally rbi-backlight does not work with it. Question is if you will be able to quickly make a solution to this issue.

**Comment by linusg** [comment]
> Question is if you will be able to quickly make a solution to this issue.

I don't have a functioning display right now, so no. Feel free to submit a tested PR based on the changes in https://github.com/linusg/rpi-backlight/pull/48 :)

**Comment by p1r473** [comment]
Hi all,
Here's my fix 
__init__.py:
```python
import lsb_release
```
```python
_BACKLIGHT_SYSFS_PATHS = {
    BoardType.RASPBERRY_PI: (
    "/sys/class/backlight/10-0045/" 
    if lsb_release.get_distro_information()['CODENAME'] == 'bullseye' 
    else "/sys/class/backlight/rpi_backlight/"),
    BoardType.TINKER_BOARD: "/sys/devices/platform/ff150000.i2c/i2c-3/3-0045/",
    BoardType.TINKER_BOARD_2: "/sys/devices/platform/ff3e0000.i2c/i2c-8/8-0045/",
}
```

**Comment by p1r473** [comment]
https://github.com/linusg/rpi-backlight/pull/48#issuecomment-1196913338
