### ISSUE TITLE
PermissionError not available in Python lower than 3.3

### ISSUE THREAD

**Issue by c-s-n** [linusg/rpi-backlight#5]
Not having set up the (recommended) backlight permissions will result in the following error on Python 2.7:
```
File "/usr/local/lib/python2.7/dist-packages/rpi_backlight.py", line 103, in set_power
    except PermissionError:
NameError: global name 'PermissionError' is not defined
```
This is because it has just been [introduced with Python 3.3](https://www.python.org/dev/peps/pep-3151/).

A possible solution would be to create your own `PermissionError` class, if it is not yet there. This will however not be thrown, so you also need to catch `OSError` and check `errno` for `EPERM`.

**Comment by linusg** [comment]
Thanks for catching this! So, if I understand correctly it would be fine catching the OSError only? Or how can I make sure it works with both major Python versions?
I'll try around a bit and publish a fix.

**Comment by linusg** [comment]
Should be fixed as of https://github.com/linusg/rpi-backlight/commit/dbc9e04fd28301ac031c1a12a338324c8b403f3f. A release is made on GitHub as well as on the PyPI. Just update with `pip install -U rpi_backlight` and you should be ready to go!
I might reopen this if you still encounter issues.

**Comment by c-s-n** [comment]
I can confirm that now the expected console message is shown, given that permissions are insufficient.

**Comment by linusg** [comment]
Perfect, thanks! :smiley:
