### ISSUE TITLE
Support for Microsoft Surface RT Tablet

### ISSUE THREAD

**Issue by apandada1** [linusg/rpi-backlight#53]
Hi, can you add support for the Microsoft Surface RT Tablet? [It supports the RPi OS](https://openrt.gitbook.io/open-surfacert/surface-rt/linux/root-filesystem/distros/raspberry-pi-os), and your software works with some tweaks.

The backlight is controlled by `/sys/class/backlight/backlight` (instead of `/sys/class/backlight/rpi_backlight`).

I edited that in `__init.py__` and it works. However, it would be great if this is included in this software.

**Comment by linusg** [comment]
PRs welcome, I'm not going to add this myself.
