### ISSUE TITLE
Cron command?

### ISSUE THREAD

**Issue by impy101** [linusg/rpi-backlight#56]
Hello,

When I enter "rpi-backlight -p off" via ssh my screen turns off. When I enter "rpi-backlight -p on" it turns back on again.

I want to have it do this automatically every day, so I added this to my crontab:

```
0 23 * * * rpi-backlight -p off

0 12 * * * rpi-backlight -p on
```

but it's not doing anything. Have I missed something?

**Comment by linusg** [comment]
You probably need to provide an absolute path to the command.
