### ISSUE TITLE
Other displays

### ISSUE THREAD

**Issue by CodingSpiderFox** [linusg/rpi-backlight#6]
Are there cheap versions of the display on which the brightness can be controlled using this library?

**Comment by linusg** [comment]
Hi,
cheap displays are out there, yes. Not versions of the official one, but third party. I guess some with brightness changing possibilities too. Let me explain:

The official touch LCD uses a function most likely built into the vanilla Linux Kernel, controlling the brightness using the `sysfs` located at `/sys`. This works on almost any Linux machines, for my laptop e.g. the `sysfs` files for the backlight are located at `/sys/class/backlight/intel_backlight/`. The Arch Linux Wiki has a great explanation, including some alternatives: https://wiki.archlinux.org/index.php/backlight.

**Why am I telling you this?**

What you're looking for is a display supporting this feature. I don't have any in mind currently, which would work for the Pi OOTB, but to be honest, I've simply never needed one different to the official one :wink:
I have two for now, which is fairly enough, as I don't need a touch display for many applications. I tend to using a webbased ui and a tablet or smartphone as the "display". Just as an idea for you.

**However: I would be willing helping you on finding one. Do you need touch? Or just a display with adaptive brightness?**

If you agree on investigating using the keywords I gave, I will do that too and the chance we'll find one is pretty high.

I would then also provide the necessary Code if e.g. the `sysfs` backlight directory differs or the display uses a different method of changing the brightness.

Please let me know what you think!

**Comment by CodingSpiderFox** [comment]
Touch would be nice but I don't need it. 

I think I could also use a microcontroller instead of a raspi for that part of the project. If I use a microcontroller, maybe this one would work for me: https://www.amazon.de/dp/B01EUVJYME/ref=wl_it_dp_o_pC_nS_ttl?_encoding=UTF8&colid=338TAMV5X48EM&coliid=I2AOQNXQ3CNXUU

**Comment by linusg** [comment]
Yes, seems like a standard display for Arduino. But this is Python in combination with Linux, so this whole project won't work for you anymore.

**Comment by CodingSpiderFox** [comment]
https://de.aliexpress.com/item/Nextion-3-2-TFT-400X240-resistive-touch-screen-display-HMI-LCD-Display-Module-TFT-Touch-Panel/32670800631.html?ws_ab_test=searchweb0_0,searchweb201602_3_10152_10065_10151_10068_10344_10342_10343_10340_10341_10194_10304_10307_10060_10302_10155_10154_10056_10055_10054_10059_10534_10533_10532_100031_10099_10338_10339_10103_10102_10052_10053_10107_10050_10142_10051_10320_10321_10084_10083_10080_10082_10081_10177_10110_10111_10112_10113_10114_143_10180_10312_10313_10314_10184_10078_10079_10073_10186,searchweb201603_12,ppcSwitch_5&btsid=0b974ad6-c070-419f-94e9-ecc6ae52f60f&algo_expid=ed357732-e793-462e-9414-77bcced37ba2-1&algo_pvid=ed357732-e793-462e-9414-77bcced37ba2

maybe this one?

**Comment by linusg** [comment]
See, there are plenty of displays for both Arduino and Raspberry Pi. However, I'm not a specialist when it comes to displays, regarding the Raspi it's a difficult thing. Better ask such things in a forum for Arduino or Raspi respectively.
Of course you might come back later and open another issue, I would be happy to help, if possible.
