### ISSUE TITLE
Setting Brightness using integer duration doesn't work

### ISSUE THREAD

**Issue by pkscout** [linusg/rpi-backlight#7]
If you set the duration is the set brightness call using an integer, the time.sleep calculation in set brightness ends up as zero most of the time because you're dividing two integers.  So duration = 10 results in immediate dimming, but duration = 10.0 results in a dimming over 10 seconds.  I think the function should convert the duration to a float, or at least all the examples should use floats for the duration.

**Comment by linusg** [comment]
The behavior you describe is not always true. In Python 3 for example, `2/3` returns the expected `0.6666666666666666`, and using a `__future__` import we can achieve the same in Python 2:

```
>>> 2/3
0
>>> from __future__ import division
>>> 2/3
0.6666666666666666
>>> 
```

So https://github.com/linusg/rpi-backlight/commit/aac5208c6196ba7c1c446fa904b526a87fdc5998 will fix it. Thanks for reporting this, though!

BTW I would encourage *everyone* to finally give up using Python 2. IMHO it has too much annoying behavior and its final EOL in less than two and a half years: https://pythonclock.org/.

**Comment by linusg** [comment]
Alright it's on PyPI now. Please test and report back if it works for you!

**Comment by pkscout** [comment]
Thanks.  That did it.  And I'll look at migrating this project to Python 3.x.  '-)

I mostly do Kodi addons, and their internal python interpreter is 2.7.x, so I haven't really had a need to look at 3 much.

**Comment by linusg** [comment]
Glad I could help!
This may be off-topic, but I want to mention: folks need to hurry. Two years is not as much time, and as you've noticed, many popular software uses still Python 2 internally. I was not aware that Kodi is, but I know parts of Debian and its forks do. Luckily, Python has much less critical security issues than let's say PHP :wink:
