### ISSUE TITLE
Unable to init server

### ISSUE THREAD

**Issue by samsunix** [linusg/rpi-backlight#8]
```
pi@raspberrypi:~ $ sudo rpi-backlight-gui
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Segmentation fault
```

This kind of result.

**Comment by linusg** [comment]
Are you working from a desktop environment/is X11 running?

**Comment by samsunix** [comment]
No [I ran it By using ssh right after I executed:  "export DISPLAY=:0"  This should work] / Yes

**Comment by linusg** [comment]
So how would you expect a GUI based on GTK ti work over a plain SSH? Use the rpi-backlight command then.
Or search how to get GUI programs working over SSH.
